freebsd_instance:
  image: freebsd-11-2-release-amd64

freebsd_build_task:

  env:
    matrix:
      - node_js: "11"
        nodeArchive: "node-11.8.0"
        npmArchive: "npm-6.4.1_1"
      - node_js: "10"
        nodeArchive: "node10-10.15.1"
        npmArchive: "npm-node10-6.4.1_1"
      - node_js: "8"
        nodeArchive: "node8-8.15.0"
        npmArchive: "npm-node8-6.4.1_1"
      - node_js: "6"
        nodeArchive: "node6-6.16.0_1"
        npmArchive: "npm-node6-6.4.1_1"

  env:
    matrix:
      - abi: freebsd:11:x86:64
      - abi: freebsd:11:x86:32
        execPrefix: cbsd jexec jname=jail-11i386

  prepare_script:
    - |
      if test "$abi" = "freebsd:11:x86:32"; then
        ./scripts/configure_freebsd_ci_jail.sh $CIRRUS_WORKING_DIR;
        $execPrefix sed -i -- '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf; # use latest ports
        $execPrefix pkg update -f;
      else
        sed -i '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf; # use latest ports
      fi
    - $execPrefix pkg install -y c-ares gmake icu libnghttp2 libuv git > /dev/null
    - $execPrefix pkg add http://pkg.freebsd.org/$abi/latest/All/$nodeArchive.txz
    - $execPrefix pkg add http://pkg.freebsd.org/$abi/latest/All/$npmArchive.txz
    - $execPrefix node --version
    - $execPrefix npm --version
    - $execPrefix clang++ --version

  build_script:
    - $execPrefix ls  # debug
    - $execPrefix npm install --unsafe-perm # kicks in the build step and invokes clang via gyp machinery

publish_task:
  only_if: '!!$CIRRUS_TAG'

  env:
    AUTH_TOKEN: ENCRYPTED[a5dff23246b1739033647812162c802c324eedf8976f2c5fa0af549de6b3a243141a94460652f542cbe24465ee628f9c]

  script:
    - curl -s -d '{"tag_name":"$CIRRUS_TAG"}' -H "Authorization:token $AUTH_TOKEN" https://api.github.com/repos/am11/node-sass/releases > null
    - for file in `ls vendor/**/*.node`; do
        parent=${file%/*};
        name=${parent##*/};
        fullyQualifiedName="$pwd/$parent/${name}_binding.node";
        mv "$file" "$parent/${name}_binding.node";
        echo -e 'New filename\072 $fullyQualifiedName';
        ./scripts/upload-github-release-asset.sh github_api_token=$AUTH_TOKEN owner=am11 repo=node-sass tag=$CIRRUS_TAG filename=$fullyQualifiedName;
      done
